# Este é um arquivo de exemplo para configurar secrets no Streamlit Cloud
# Crie uma cópia deste arquivo, renomeie para .streamlit/secrets.toml 
# em seu projeto local para testes

# Credenciais de admin
[credentials]
username = "admin"
password = "admin123"

# Credenciais de cliente (opcional)
[client_users]
cliente1 = "senha123"
cliente2 = "senha456"

# Configurações SMTP para envio de emails (opcional)
[email]
smtp_server = "smtp.gmail.com"
smtp_port = 587
smtp_username = "seu-email@gmail.com"
smtp_password = "sua-senha-ou-app-password"
from_email = "seu-email@gmail.com"

# Configurações Twilio para SMS (opcional)
[twilio]
account_sid = "seu-account-sid"
auth_token = "seu-auth-token"
phone_number = "+1234567890"